spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres2
    username: postgress
    password: 2255
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always